### ISSUE TITLE
Application compatibility

### ISSUE THREAD

**Issue by susnicek** [mecotrade/kidtracker#1]
Dear developer,
first: I would like to thank you for this application you develop. I think this is something that I have been looking for a long time.
I am going to buy a kid smartwatch Q528, so my questions are as follows:
1) Is there a chance that the web application will work with this smartwatch Q528?
2) Is the application compatible with and will work on linux desktop environment (Debian)?

Thank you for your reply in advance!
Best regards, Susnicek

**Comment by mecotrade** [comment]
Thank you! To answer your questions:

1. I didn't test my web application on this precise model Q528, however, there is a good chance it will be able to communicate with such a device for the following reason. The web app implements the very same protocol that is implemented for SeTracker and FindMyKids backends, Q528 is declared to be compatible (at least) with SeTracker, that's why I'm thinking my web app should be compatible with Q528 as well.
2. The application can be both build and deployed with Docker (you can find instruction in README), so it is host OS agnostic, and have to work on Debian.

Best regards

**Comment by susnicek** [comment]
This is perfect, thank you for the information!

Best regards
